# Generated by Django 5.1.2 on 2024-10-26 23:27

import core.utils.crypto_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSHConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('password', core.utils.crypto_field.CryptoField(null=True)),
                ('private_key', core.utils.crypto_field.CryptoField(null=True)),
                ('passphrase', core.utils.crypto_field.CryptoField(null=True)),
            ],
        ),
    ]
