# Generated by Django 5.1.2 on 2024-10-26 23:33

import core.utils.crypto_field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('postgres', 'Postgres')], max_length=32)),
                ('db', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('user', core.utils.crypto_field.CryptoField(null=True)),
                ('password', core.utils.crypto_field.CryptoField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='S3Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(max_length=16)),
                ('access_key', core.utils.crypto_field.CryptoField(null=True)),
                ('secret_key', core.utils.crypto_field.CryptoField(null=True)),
                ('root', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_versions', models.IntegerField(default=3)),
                ('ssh_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs', to='config.sshconnection')),
                ('s3_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs', to='config.s3connection')),
            ],
        ),
    ]
