# Generated by Django 5.1.2 on 2024-10-27 00:37

import core.utils.crypto_field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_databaseconnection_s3connection_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='database_connection',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='config.databaseconnection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=core.utils.crypto_field.CryptoField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='user',
            field=core.utils.crypto_field.CryptoField(default=None),
            preserve_default=False,
        ),
    ]
