# Generated by Django 5.1.2 on 2024-10-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_config_database_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='key',
            field=models.CharField(default='undefined', max_length=64),
            preserve_default=False,
        ),
    ]
