# Generated by Django 5.1.2 on 2024-10-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_config_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3connection',
            name='bucket',
            field=models.CharField(default='1f39f2f5-corex', max_length=128),
            preserve_default=False,
        ),
    ]
