# Generated by Django 5.1.2 on 2025-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_s3connection_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='type',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('docker_postgres', 'Docker Postgres')], max_length=32),
        ),
    ]
