# Generated by Django 5.1.2 on 2025-04-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_databaseconnection_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='auto_build',
            field=models.BooleanField(default=False),
        ),
    ]
