# Generated by Django 5.1.2 on 2025-04-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_config_auto_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshconnection',
            name='type',
            field=models.CharField(choices=[('password', 'Password'), ('private_key', 'Private Key')], default='password', max_length=32),
        ),
    ]
