# Generated by Django 5.1.2 on 2025-04-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_sshconnection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshconnection',
            name='type',
            field=models.CharField(choices=[('password', 'Password'), ('private_key', 'Private Key'), ('private_key_with_passphrase', 'Private Key With Passphrase')], default='password', max_length=32),
        ),
    ]
