x-restart-policy: &restart_policy
  restart: unless-stopped
x-healthcheck-defaults: &healthcheck_defaults
  interval: 5s
  timeout: 5s
  retries: 10
  start_period: 30s
x-app-defaults: &app_defaults
  <<: *restart_policy
  stop_grace_period: "3s"
  volumes:
    - ./data:/app/data
  depends_on:
    redis:
      condition: service_healthy
services:
  app:
    <<: *app_defaults
    build: .
    command: make gunicorn
    ports:
      - "${ENTRY_PORT:-15000}:8000"
    healthcheck:
      <<: *healthcheck_defaults
      test: [ "CMD-SHELL", "wget -q --spider http://0.0.0.0:8000/api/v1/ready || exit 1" ]
  celery:
    <<: *app_defaults
    build: .
    command: make celery
    depends_on:
      app:
        condition: service_healthy
  redis:
    <<: *restart_policy
    image: redis:7.4.1-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      <<: *healthcheck_defaults
      test: [ "CMD", "redis-cli", "ping" ]
volumes:
  redis_data:
