# Generated by Django 5.1.2 on 2024-10-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='storage',
            field=models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], default='local', max_length=16),
            preserve_default=False,
        ),
    ]
