# Generated by Django 5.1.2 on 2025-04-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflow_active_workflow_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
